### PR TITLE
Combine with pages-toggle

### PR DESCRIPTION
**Pull request by mertkahyaoglu**

### CODE REVIEW

**Comment by benbalter** [comment]
@mertkahyaoglu can you describe a bit more about what you're proposing here and why?

**Comment by mertkahyaoglu** [comment]
Created this PR after the discussion [here](https://github.com/benbalter/pages-toggle-bookmarklet/issues/1). It was a while ago. I also wanted to test the new review feature for a good reason 😬

**Comment by benbalter** [comment]
I think I'd like to keep the separate, as their goals are distinct.

**Comment by mertkahyaoglu** [comment]
👍

**Pull request closed without merging**
